# Generated by Django 5.1.4 on 2025-01-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exam_id_remove_exam_questions_alter_exam_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
